spring.application.name=puntoVentaHM.pos_hamburguesas

spring.datasource.url=jdbc:postgresql://localhost:5432/punto_ventas
spring.datasource.username=postgres
spring.datasource.password=maiz564
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.caja.umbral-retiro-seguridad=3000
